pauta:
  url:
    host: http://localhost:8080
    path: /pauta

springdoc:
  api:
    title: My API
    description: This is my API description
    version: 1.0.0
  api-docs:
    path: /api-docs
  app:
    proxy: ${pauta.url.host}/swagger-ui.html


spring:
  r2dbc:
    host: localhost
    port: 5432
    data-base: database-name
    username: postgres
    password: postgres

gateway:
  url: http://localhost:8080/v1/usuario/valid-cpf/